### ISSUE TITLE
Group Operation Counting

### ISSUE THREAD

**Issue by rheitjoh** [upbcuk/upb.crypto.math#14]
The ability to count group operations such as ops, squarings and inversions, as well as exponentiations is useful to 
1. find bugs by comparing the actual number of ops to what one would expect from the algorithm, and
2. benchmark an implemented scheme in a way that is mostly independent from the speed of the implementation.

# Requirements

The requirements for such a feature would be as follows:
1. Should be able to track group operations, inversions, squarings (interesting for elliptic curves), exponentiations and multi-exponentiations per group.
2. Simple to implement to not complicate the code more.
3. Easy to use.

# Ideas

@JanBobolz had the idea of letting the `DebugGroupImpl` do the counting and enabling support for tracking multi-exponentiations via the `LazyGroup`. `DebugGroupImpl`, on its own, cannot properly track operations done in exponentiation algorithms since it just uses `Zn` multiplication to do the exponentiation, resulting in no actual group operations done that one could track. It is possible to calculate the group operations that would theoretically be done in something like binary square & multiply or wnaf, but we would need to know exactly which algorithm actually ends up being chosen. This also does not solve the issue of tracking multi-exponentiations.

These issues are fixed by using `LazyGroup`. `LazyGroup` can update the information stored in `DebugGroupImpl` whenever it performs a multi-exponentiation, enabling tracking of multi-exponentiations. Furthermore, it uses regular exponentiation algorithms, instead of the `Zn` multiplication, meaning that group operations used in, for example, wnaf, are tracked normally. The disadvantage of this is that evaluation becomes much less efficient since we don't use the efficient multiplication for exponentiation.

# Proposal and Prototype

I have implemented the above approach on [this branch](https://github.com/upbcuk/upb.crypto.math/tree/op-counting).
It counts number of operations, inversions, squarings, exponentiations and multi-exponentiations (multi-exponentiations are tracked in the form of a list of the number of terms in each multi-exponentiation done) in the `DebugGroupImpl` instance.
To interact with these counters, methods for incrementing and resetting the counters, and retrieval of the numbers have been added to `DebugGroupImpl`. The counters have not been added to the representation as this seems not useful and just increases size of the representation.

`LazyGroup` has been modified in that whenever it is initialized with a `DebugGroupImpl`, it checks this and sets a specific boolean variable, indicating that it will track exponentiations and multi-exponentiations in the given group.
Whenever it performs the wnaf exponentiation or multi-exponentiation, the data in the debug group is updated.
One could avoid the class variable by checking for `DebugGroupImpl` explicitly before each (multi-)exponentiation, but this probably induces a slightly higher runtime because of the needed equality check.

## Example
An example of a multi-exponentiation is given below. 

```java
DebugGroupImpl debugGroup = new DebugGroupImpl("D1", BigInteger.valueOf(1000000));
LazyGroup lazyGroup = new LazyGroup(debugGroup);
GroupElement elem = lazyGroup.getUniformlyRandomNonNeutral();
GroupElement elem2 = lazyGroup.getUniformlyRandomNonNeutral();
elem = elem.op(elem2.pow(16));
elem = elem.op(elem2.pow(16));
elem = elem.computeSync();

System.out.println("Ops: " + debugGroup.getNumOps());
System.out.println("Sqs: " + debugGroup.getNumSquarings());
System.out.println("Invs: " + debugGroup.getNumInversions());
System.out.println("Exps: " + debugGroup.getNumExps());
System.out.println("MultiExps: " + debugGroup.getMultiExpData().toString());
```
Output:
```
Ops: 32768 // precomputation for both terms in multi-exponentiation 
           // should only be done once since both bases are the same but that is a current bug
Sqs: 7
Invs: 0
Exps: 0
MultiExps: [2] // multiexponentiation contains two terms
```

**Comment by JanBobolz** [comment]
I'd prefer not touching LazyGroup (or any of those `Group`s) for counting. Instead, I propose the following mechanism:

- The `GroupImpl` interface gets an additional `multiexp()` method. This is optional to implement (in the same vein, we should make `pow()` optional to implement). Potentially, we would also want to expose `GroupElementImpl::precompute()` (similarly optional to implement).
- `LazyGroup`, `BasicGroup`, etc. would ask the `GroupImpl` "do you implement your own (multi-)exponentiation?". If so, any exponentiation and precomputation calls would be forwarded to the `GroupImpl`. Of not, the groups would fall back to a generic exponentiation algorithms.
- For our current `GroupImpl`s: most of them don't have any sort of "native" exponentiation, so they wouldn't implement the `pow()`, etc. methods, so everything would work as it does right now: the `Group` takes care of (multi-) exponentiation, the `GroupImpl` basically just does `op()`.
- The `DebugGroupImpl` could then run in a kind of dual-mode: if it exposes the `pow()`, etc., any (multi-)exponentiations would be forwarded directly and could be counted. If it doesn't expose these methods, it would see only `op()`s, allowing to count the total number of group operations (including ones that happen within a (multi-)exponentiation). The former version would replace your `LazyGroup` counting hack. 

I haven't thought this through completely, but something like this is my current favorite. Any ideas? Comments?

**Comment by rheitjoh** [comment]
>     * The `DebugGroupImpl` could then run in a kind of dual-mode: if it exposes the `pow()`, etc., any (multi-)exponentiations would be forwarded directly and could be counted. If it doesn't expose these methods, it would see only `op()`s, allowing to count the total number of group operations (including ones that happen within a (multi-)exponentiation). The former version would replace your `LazyGroup` counting hack.

How does this "exposing the `pow()`" work? You would somehow need to tell the `DebugGroupImpl` which exponentiation/multi-exponentiation algorithm the original group would have used so that it can use the same one, right? Otherwise it cannot count the operations that would have been done in the original group. Does this mean we make the `DebugGroupImpl` configurable in the sense of letting the user choose an exponentiation/multi-exponentiation algorithm?

**Comment by JanBobolz** [comment]
"exposing `pow()`": easiest way would be to add a `boolean implementsOwnPow()` to the `GroupImpl` interface, which the `Group` would check. The `DebugGroupImpl` would be configurable in whether it replies true or false there.

> You would somehow need to tell the DebugGroupImpl which exponentiation/multi-exponentiation algorithm the original group would have used so that it can use the same one, right?

Very generally: I would never count anything that happens internally within a `GroupImpl` (e.g., I wouldn't start counting the operations that mcl does internally for `pow()`). As far as counting is concerned, any calls on `GroupImpl` all count as a single operation each (even if `pow()` calls may, of course, internally trigger some group operations, I would just count it as "one `pow()`"). Similarly, the `DebugGroupImpl` would just count the number of method calls to any of its methods. What `DebugGroupImpl` internally does for `pow()` doesn't matter, you may as well implement it as Zn multiplication.

So if `DebugGroupImpl::implementsOwnPow()`, the `Group` would forward all `pow()` calls, so `DebugGroupImpl` counts number of `pow()` executed.
If `not DebugGroupImpl::implementsOwnPow()`, then the `Group` uses whatever exponentiation algorithm it's configured for (let's say you can tell `LazyGroup` which multiexp algorithm it should use) and then the `Group` will just do a bunch of `op()` calls on the `DebugGroupImpl` in the course of running that algorithm, which the `DebugGroupImpl` would count. So that way, you get a _total_ number of group operations.

**Comment by rheitjoh** [comment]
So we will use the `multiexp()` method to track multiexponentiations? Will there be a `implementsOwnMultiExp()` to enable this simular to regular exponentiation? Do we still want to track number of bases for each one?

Sounds reasonable to me otherwise.

**Comment by JanBobolz** [comment]
Exactly. That's the current plan :)

**Comment by rheitjoh** [comment]
Okay, I'll implement a new prototype based on the plan.

**Comment by rheitjoh** [comment]
Since `LazyGroup`'s `compute` does the evaluation in parallel and does not block, there can be problems in that if you print out the number of operations after calling `compute` you will not get the actual result if `compute` has not finished yet. Do we want to add blocking logic to the count retrieval methods for `DebugGroupImpl` or are we happy with telling the user to use `computeSync`? The latter seems annoying since the user has to take their code and replace the `compute` calls with `computeSync`. Maybe just some kind of "wait for all executions to finish" method on the `LazyGroup` would be the simplest idea?

**Comment by JanBobolz** [comment]
hm. This is indeed slightly annoying. 

I'm not a huge fan of a "wait for all executions to finish" method because it's never used in production and it's (I think) not that easy to implement. 

Maybe we can tell the user to call getRepresentation() on whatever they're computing (e.g., `scheme.encrypt(pk, m).getRepresentation(); group.getNumberOfOps();`. 
Then the story is "you can never be sure that something will have been computed, unless you print the result". That sounds somewhat reasonable to me. But I agree, this is not ideal. 

I don't know 🙂 - I'd have to think about it more.

**Comment by JanBobolz** [comment]
Another idea (not sure whether it's good): What about a `CountingGroup` wrapper around a `Group` that behaves like the original group, but immediately calls `computeSync()` after every `compute()` call?

**Comment by rheitjoh** [comment]
So if I understand correctly, the idea is that the `CountingGroup` extends `LazyGroup` and then extends `compute()` in the way you said? Then we could also include an automatic instantiation of `LazyGroup` with `DebugGroupImpl` in the constructor of `CountingGroup`, which would be nicer than telling them to instantiate `LazyGroup` using `DebugGroupImpl`.

**Comment by JanBobolz** [comment]
Not necessarily `CountingGroup extends LazyGroup`, but rather `new CountingGroup(Group forExampleLazyGroup)`. This way, we could reuse the same thing for implementations other `Group`s, too.

**Comment by rheitjoh** [comment]
So the idea is that the user can also use a `BasicGroup` there, if desired? That makes sense.

**Comment by rheitjoh** [comment]
Does the user really want to count both at the same time though? I feel like if you want to count exponentiations as a unit, you do not want to count the group operations done within them since you are just doubly counting then.

**Comment by JanBobolz** [comment]
> I feel like if you want to count exponentiations as a unit, you do not want to count the group operations done within them since you are just doubly counting then.

They're distinct counters, so in my mind, this just means the user doesn't have to run his program twice to get the result of both count types.
I'm not married to that idea. Feel free to think about it and then decide on anything reasonable.

**Comment by rheitjoh** [comment]
> > I feel like if you want to count exponentiations as a unit, you do not want to count the group operations done within them since you are just doubly counting then.
> 
> They're distinct counters, so in my mind, this just means the user doesn't have to run his program twice to get the result of both count types.

You are suggesting two different group operation counters, one for regular group operations and one for group ops done within a (multi-)exponentiation, right?

I have thought about adding separate group operation counters just for group operations done in (multi-)exponentiations, but  I don't think that is practically possible since the (multi-)exponentiation algorithm calls the `DebugGroupImpl` `op()` and the debug group does not know where the call came from. So we would either need a second kind of `op()` or adapt the behaviour of the (multi-)exponentiation algorithms to change when instantiated with a debug group (which would pollute the production code again).

**Comment by JanBobolz** [comment]
> I have thought about adding separate group operation counters just for group operations done in (multi-)exponentiations, but I don't think that is practically possible since the (multi-)exponentiation algorithm calls the DebugGroupImpl op() and the debug group does not know where the call came from.

Oh, sorry. I didn't mean to say that you explicitly count the number of "regular group ops" vs number of "group ops triggered by (mult-)exponentiation". My point was to do the following:

- `CountingGroup` instantiates two `DebugGroupImpl`s (and, hence, a `Group` for each, too). One that's set to implement (multi-) exponentiation (1), one that's set not to (2).
- All group operations of the `CountingGroup` are done on both groups (i.e. a `CountingGroupElement` consists of two `GroupElement`s). 
- Then we provide a nice interface to get the following numbers:
  - "Number of group operations total" (using count of (2) as described in first bullet point)
  - "Number of (multi-)exponentiation" (using count of (1))
  - "Number of group ops outside of (multi-)exponentiations" (using count of (1))

**Comment by rheitjoh** [comment]
Okay, I have implemented a new `CountingGroup` prototype based on our discussion. This does not yet include any changes to our bilinear group code.

As suggested by @JanBobolz, the `CountingGroup` includes two `DebugGroupImpl` instances, one that counts total group operations and one that counts only separate group operations as well as exponentiations and number of terms in each multi-exponentiation. This allows for tracking both at once while keeping user involvement at a minimum.

In my implementation, it encapsulates two `LazyGroup` instances which then contain the two `DebugGroupImpl` instances. This allows `CountingGroup` to implement the `Group` interface which can be used to overwrite `compute()` with `computeSync()`.
`CountingGroup` also includes methods to retrieve all the tracked counters and data. Furthermore, I implemented a method that automatically formats all data as a `String` for easier printing to console. The output  so far looks as follows:

```
----- Total group operation data: -----
    Number of Group Operations: 65545
    Number of Group Inversions: 1
    Number of Group Squarings: 8
----- Group operation data without operations done in (multi-)exp algorithms: -----
    Number of Group Operations: 1
    Number of Group Inversions: 1
    Number of Group Squarings: 1
----- Other data: -----
    Number of exponentiations: 1
    Number of terms in each multi-exponentiation: [4]
    Number of retrieved representations (via getRepresentation()): 1
```

Produced by the code:
```java
CountingGroup countingGroup = new CountingGroup("test", 1000000);
GroupElement elem = countingGroup.getUniformlyRandomNonNeutral();
GroupElement elem2 = countingGroup.getUniformlyRandomNonNeutral();
GroupElement elem3 = countingGroup.getUniformlyRandomNonNeutral();
GroupElement elem4 = countingGroup.getUniformlyRandomNonNeutral();

elem.pow(10).op(elem2.pow(10)).op(elem3.pow(10)).op(elem4.pow(10)).compute();

elem.getRepresentation();

elem.pow(10).computeSync();

elem.op(elem).op(elem2).inv().compute();

System.out.println(countingGroup.formatCounters());
```

As you can see, `CountingGroup` accepts the same arguments as `DebugGroupImpl` and uses these to instantiate the latter.

**Comment by rheitjoh** [comment]
Ok I have implemented `CountingBilinearGroup` now which is basically the same thing but for bilinear groups. It also allows for counting pairings and has a method for formatting all data in the bilinear group as a string.

It is implemented very similar to `CountingGroup` in that it wraps two `LazyBilinearGroup` instances, one for counting total operations and one for counting (mutli-)exponentiations as one unit. There is no `BilinearGroupImpl` implementation since there is no `GroupImpl` which would make sense so the provider does not implement the `BilinearGroupProvider` interface (requires a `BilinearGroupImpl` method).

Regarding integration with `BilinearGroupFactory`: I have replaced the `DebugBilinearGroupProvider` with the `CountingBilinearGroupProvider` so you would get the `CountingBilinearGroup` when setting `debugMode` to `true` in the `BilinearGroupFactory`. Aside from that I have kept the `BilinearGroupFactory` methods the same, so no special method for creating debug bilinear groups.

As a next step, I think a class for exporting the operation data as a CSV file would be interesting. Then you can directly create LaTex tables from that.

**Comment by JanBobolz** [comment]
Fixed with https://github.com/upbcuk/upb.crypto.math/pull/24
