### ISSUE TITLE
Math Rewrite Bug: Recursive Group Ops lead to Exponential Blowup in Evaluation

### ISSUE THREAD

**Issue by rheitjoh** [upbcuk/upb.crypto.math#17]
The following code leads to an exponential blowup in group operations performed:
```java
DebugGroupImpl debugGroup = new DebugGroupImpl("D1", BigInteger.valueOf(1000000));
LazyGroup lazyGroup = new LazyGroup(debugGroup);
GroupElement elem = lazyGroup.getUniformlyRandomNonNeutral();
for (int i = 0; i < 5; ++i) {
    elem = elem.op(elem);
}
elem.computeSync();
```

The cause for this is that a tree of group operations is constructed which grows exponentially due to reusing `elem` in each turn. The `LazyGroup` evaluation does not intelligently reuse already computed operations, and instead evaluates every group operation separately, resulting in the exponential number of group operations.

**Comment by JanBobolz** [comment]
Should be fixed in 0358173b0fa11edad81a72da6fa71e822ee1597d
