### ISSUE TITLE
Math Rewrite Bug: Precomputations Are Not Reused

### ISSUE THREAD

**Issue by rheitjoh** [upbcuk/upb.crypto.math#18]
The following code leads to more group operations than expected:
```java
DebugGroupImpl debugGroup = new DebugGroupImpl("D1", BigInteger.valueOf(1000000));
LazyGroup lazyGroup = new LazyGroup(debugGroup);
GroupElement elem = lazyGroup.getUniformlyRandomNonNeutral();
for (int i = 0; i < 5; ++i) {
    elem.pow(16).computeSync();
}
```
This is due to the precomputations for the exponentiation being done each time, instead of being cached as should be the case.

**Comment by JanBobolz** [comment]
Should be fixed in 0358173b0fa11edad81a72da6fa71e822ee1597d
