### ISSUE TITLE
Snapshot Builds (for all upbcuk projects)

### ISSUE THREAD

**Issue by rheitjoh** [upbcuk/upb.crypto.math#21]
I am posting this in the math issue section, but this obviously applies to all upbcuk projects.

OSS Nexus Repository allows us to host snapshots as well. Currently we had only planned to make use of composite builds for development instead of snapshots.

# Use Case Scenarios

I have written down some use case scenarios that came to mind and how one would solve these using either snapshot or composite builds.

## Scenario 1
You are working on craco on branch `feature` and are simultaneously making changes to math. You want these changes to be integrated while working on craco.

### Using Snapshot
Every time you make a change to math, you need to build and locally publish the new math build as a snapshot so that craco can use it. Only master builds are uploaded to the snapshot repo so can only use local build here.

### Using Composite Build
You create a `feature` branch for math and do your changes there. The composite build script includes the math build automatically in your craco project as long as that branch is checked out in git.

### Comparison
Composite Build is better here since you don't need to do any manual building and publishing to a local repo.

## Scenario 2
You are working on craco on branch `feature` and are using a specific release version of math. You don't intend to change math.

Gradle just automatically does the dependency resolution as usual. No need to do any snapshot publishing or composite build.

## Scenario 3
You are working on cranco on branch `feature` and are using a version of math on branch `mbranch`. You don't intend to make any changes to math.

### Using Snapshot
You need to build and locally publish the new math build as a snapshot so that craco can use it. Only master builds are uploaded to the snapshot repo so can only use local build here.

### Using Composite Build
You check out `mbranch` in the math git and use the `useCurrentBranch` parameter so that the craco build script automatically includes that math build.

### Comparison
Snapshot has the advantage that you always know that the right version is being used by gradle, unless you have messed up in the versioning and have different math builds with the same version number. This can happen however and can be annoying as well as hard to track down. Composite build is simple to use, but you need to make sure that the `mbranch` branch is actually checked out when working on craco.I think composite builds are preferable here.

## Scenario 4
You are working on craco on branch `feature` and are using a version of math on branch `master`. 
You don't intend to make any changes to math.

### Using Snapshot
Snapshot builds on master are automatically published to the repository. Gradle automatically does the dependency resolution for you.

### Using Composite Build
You check out `master` in the math git and the craco build script automatically includes it in the build.

### Comparison
Here Snapshots win since you don't really need to do anything, although using the composite builds is not too hard either.

# Overall
Scenario 4 does present a use case for snapshot builds. Whenever you want to make any changes to the dependency, or use a version from a specific branch, composite builds become easier to use since you avoid any manual build and local publishing process.  The composite build using versions from specific branches is also nice in that you don't run into problems where there are different builds with the same version number, e.g. if you are still working on that specific version. There can however be problems if you have checked out the wrong branch of the dependency since the `useCurrentBranch` parameter would mean the build script happily uses whatever branch is currently checked out. This should be easier to notice though if you, at any point, have the git folder open and can see the checked out branch. Another advantage of composite builds is that IntelliJ automaticall includes the included projects source which means you can jump to source without having to open math in a different project window.

I think the main question is whether we want to offer snapshot builds in addition to the composite build script. Once could add a parameter to disable the composite build script and revert back to snapshots if desired. Then one could make use of snapshot builds for scenario 4. In general though, I think that local snapshots are pointless with our composite build script.

Right now, I would say we remove the snapshot travis code so it does not constantly fail. Once we have the repository up and running, we can add snapshot builds back in if we feel the need.

**Comment by JanBobolz** [comment]
Nicely reasoned, thanks! I agree with your conclusion that local snapshots don't seem to be all that useful. There are probably scenarios for this, but they seem to be rare and setting up the composite build is easy enough if you need any "advanced" stuff out of our library that's not supplied by the current full build on maven central.
