### ISSUE TITLE
Sliding Window (Multi-)Exponentiation: Handling Negative Exponents

### ISSUE THREAD

**Issue by rheitjoh** [upbcuk/upb.crypto.math#29]
# Multi-Exponentiation
Currently, we do not have the standard interleaved sliding window multi-exponentiation integrated into `LazyGroup` due to the lack of handling of negative exponents.

The wNAF algorithm handles negative exponents as follows:
1. The exponent is negated such that it is positive.
2. During computation of the wNAF representation, the wNAF digits are negated. This is possible since we assume to have access to the inverted precomputation due to efficient inversion.

This approach does not work the same way for the regular sliding window algorithm as we cannot assume inversion to be cheap.
In our discussion @JanBobolz and I have identified some different approaches to handle negative exponents:

### Approach 1 (A1)
Invert the basis. Meaning, that given a negative exponent e with basis g, we invert g and act as if it was a whole new group element. The precomputation would then be done for g as usual.

One problem with this is that `precomputePow()` is intended to be run by the user on each basis to do the precomputations for later. For a negative exponent, the user would need to be aware of this fact and call `precomputePow` on the inverted basis instead. This is where our previous approach using expressions had an advantage since the precomputation there was able to automatically detect the fact that a basis needed to be inverted.

### Approach 2 (A2)
Take the absolute of every exponent but store the fact that it is actually negative. Then, when accessing the precomputations for this element, we invert every precomputation we access.

### Comparison 
We will probably need some actual benchmarks to compare these properly. Plus I don't actually know how long inversions take in Z_p compared to group operations.

Most likely, there is a tradeoff since in case the inverted group element is used many times, doing a new precomputation might be better.

**Comment by JanBobolz** [comment]
> We will probably need some actual benchmarks to compare these properly. Plus I don't actually know how long inversions take in Z_p compared to group operations.

Inversion in G1 is roughly as expensive as negation in Zp (since that's exactly what happens there, the point (x,y) becomes (x,-y)). In G2, an inversion is worth two negations in Zp. In GT it's 12. (All values are for BN).

However, in my mind, no negations will happen in Zp, only over the integers. So if the user writes g^-2, which is very quick to compute (few bits in exponent), we shouldn't go and normalize that to g^(p-2), which takes very long to compute (many bits in exponent). 

So when handling these multiexponentiations, let's always negate over the integers, otherwise we'll likely lose some of the user's static optimization.

**Comment by rheitjoh** [comment]
Seems like the first approach would probably be preferable for something like GT then. Perhaps we should reintroduce the `estimateCostOfInversion` method again. Then we could automatically choose which approach to take.

**Comment by JanBobolz** [comment]
Ok. So `estimateCostOfInversion` is then used to decide between between A1 and A2?

**Comment by rheitjoh** [comment]
Yes. That was previously also used to decide when to use wNAF versus the regular sliding window algorithm. So that would adress issue #27 as well.

**Comment by JanBobolz** [comment]
Okay. Go for it! 👍

**Comment by rheitjoh** [comment]
Did some basic benchmarking for multi-exponentiations using the Mcl group. This is with a multiexponentiation containing only negative exponents chosen at random. Mode is average time and the precomputation is recomputed in each invocation.

Window Size 4
|Benchmark|Mode|Threads|Samples|Score|Score Error (99.9%)|Unit|Param: groupSelection|
|----------------|-------|-----------|------------|--------|--------------------------|-----|------------------------------|
|measureSlidingA1|avgt|1|6|436.186595|6.962611|us/op|G1|
|measureSlidingA2|avgt|1|6|595.653265|193.988387|us/op|G1|
|measureSlidingA1|avgt|1|6|4035.725175|356.772890|us/op|GT
|measureSlidingA2|avgt|1|6|37246.643268|1604.963991|us/op|GT|

Window Size 8
|Benchmark|Mode|Threads|Samples|Score|Score Error (99.9%)|Unit|Param: groupSelection|
|----------------|-------|-----------|------------|--------|--------------------------|-----|------------------------------|
|measureSlidingA1|avgt|1|6|2474.102349|252.443885|us/op|G1|
|measureSlidingA2|avgt|1|6|2489.110615|98.360100|us/op|G1|
|measureSlidingA1|avgt|1|6|10323.774253|5330.986425|us/op|GT|
|measureSlidingA2|avgt|1|6|27427.805379|1011.009248|us/op|GT|

As expected, a larger window size and faster inversion (G1) suits the second approach better. Overall though, A1 is better pretty much everywhere.

I find it a bit weird though that A2 is significantly better with window size 8 compared to 4. The precomputation should be done anew in each run since the terms are built new in each execution (due to all negative exponents). So I would not expect an improvement there. I think based on the G1 results its pretty clear that the larger window size is having a noticeable effect though so I think its being recomputed each time as expected.

Will follow this up with some benchmarking where precomputations are actually reused for A2 since it allows for that.

**Comment by rheitjoh** [comment]
Same Benchmarks but now A2 reuses precomputations. Each iteration takes 5 seconds so the precomputation is reused for how ever many invocations fit into that time span.

Window Size 4
|Benchmark|Mode|Threads|Samples|Score|Score Error (99.9%)|Unit|Param: groupSelection|
|----------------|-------|-----------|------------|--------|--------------------------|-----|------------------------------|
|measureSlidingA1|avgt|1|6|485.528449|380.841525|us/op|G1|
|measureSlidingA2|avgt|1|6|412.706322|500.205179|us/op|G1|
|measureSlidingA1|avgt|1|6|4027.562707|97.273287|us/op|GT|
|measureSlidingA2|avgt|1|6|36427.983383|1494.433223|us/op|GT|


Window Size 8
|Benchmark|Mode|Threads|Samples|Score|Score Error (99.9%)|Unit|Param: groupSelection|
|----------------|-------|-----------|------------|--------|--------------------------|-----|------------------------------|
|measureSlidingA1|avgt|1|6|2780.555200|2542.963536|us/op|G1|
|measureSlidingA2|avgt|1|6|266.973660|17.313635|us/op|G1|
|measureSlidingA1|avgt|1|6|9801.616231|1007.556859|us/op|GT|
|measureSlidingA2|avgt|1|6|21367.908625|855.368389|us/op|GT|

If you can reuse the precomputation, A2 actually becomes worth it in groups with fast inversion such as G1.

**Comment by rheitjoh** [comment]
Same Benchmarks but now both algorithms reuse their precomputations. For A1 this is done by converting the multiexponentiation to non-negative exponents during setup before each iteration.

Window Size 4
|Benchmark|Mode|Threads|Samples|Score|Score Error (99.9%)|Unit|Param: groupSelection|
|----------------|-------|-----------|------------|--------|--------------------------|-----|------------------------------|
|measureSlidingA1|avgt|1|6|310.835843|190.621568|us/op|G1|
|measureSlidingA2|avgt|1|6|454.572310|486.636587|us/op|G1|
|measureSlidingA1|avgt|1|6|851.537934|44.496054|us/op|GT|
|measureSlidingA2|avgt|1|6|36165.678043|1188.931551|us/op|GT|

Window Size 8
|Benchmark|Mode|Threads|Samples|Score|Score Error (99.9%)|Unit|Param: groupSelection|
|----------------|-------|-----------|------------|--------|--------------------------|-----|------------------------------|
|measureSlidingA1|avgt|1|6|264.249613|203.393533|us/op|G1|
|measureSlidingA2|avgt|1|6|315.399062|288.570561|us/op|G1|
|measureSlidingA1|avgt|1|6|579.236621|25.569786|us/op|GT|
|measureSlidingA2|avgt|1|6|20986.046511|1372.982309|us/op|GT|

**Comment by JanBobolz** [comment]
Let's do some quick napkin math for a single-base exponentiation, assuming there already are precomputed values.

Let's say our exponent is 256 bits. Let w be our window size. This means we access the precomputations at most 256/w times. However, the precomputation contains 2^w values.

To for w = 4: I'd expect A2 to do at most 64 additional inversions (one for every access). For A1, I'd expect 16 inversions (assuming you invert the old precomputation). 

For w = 8: I'd expect A2 to do at most 32 additional inversions (one for every access). For A1, I'd expect 256 inversions (assuming you invert the old precomputation).

**Comment by rheitjoh** [comment]
So the enormous inversion costs in the GT benchmarks stem from the fact that an inversion in our Mcl GT costs 184 microseconds on average while in G1 it only consts 0.681 microseconds on average. The latter is still more expensive than our own BN group where inversion in G1 costs just 0.14 microseconds on average. GT inversion costs ~0.68 in our BN group, so mclwrap GT inv costs ~300 times as much!

The large cost of Mcl GT inversion is due to our odd implementation via an exponentiation. The inv method for GT is listed in the [Mcl API document] (https://github.com/herumi/mcl/blob/master/api.md) under `mclBnGT_inv` but is not included in the Java FFI for some reason.

**Comment by feidens** [comment]
We could implement it in the Mcl Java API and do a pull request on the original repository, starting from [here](https://github.com/herumi/mcl/blob/master/ffi/java/com/herumi/mcl/MclJNI.java).

**Comment by rheitjoh** [comment]
Yes I am looking into that.

**Comment by feidens** [comment]
Also we could ask the developer by creating an issue and marking that as highly optional.

**Comment by feidens** [comment]
Why do we want to invert in GT?

**Comment by rheitjoh** [comment]
Isnt that a basic functionality that should work? Here, mainly so that the multiexponentiation works properly since I am comparing performance of our different approaches for handling negative exponents in the different groups.

**Comment by feidens** [comment]
Thank you. I thought I missed some scheme that really uses this.

Of course I'm with you that it should work properly and somehow efficiently.

**Comment by JanBobolz** [comment]
Right. I've implemented the inversion via exponentiation as a "quick fix" because the method was missing from the JNI stuff as you've described, Raphael. Would be cool if we could add that method. 

However, as Fabian notes, inversion in GT should happen rarely in practice, so it's not like this has a huge priority. Would still be cool, though.

**Comment by JanBobolz** [comment]
Okay, so what's our high level conclusion of all of this and how do we implement this now?

**Comment by rheitjoh** [comment]
Well, actually wNAF seems to be always better than A2 so the choice is more between A1 and wNAF now. Problem is, its very hard to make the right choice in general since its influenced by so many factors:
- The exact ratio of inversion to op cost.
- The window size. Larger window size is better for wNAF since A1 takes more time for its precomputation then.
- The number of negative exponents. More negative exponents means more precomputations to be done for A1.
- Whether precomputations are already available for wNAF.
- Whether precomputations are available for A1. There currently is no easy way for the user to do precomputations for an inverted base, that would need to be added. Currently you could invert the base, compute the concrete value, rewrap it in a `LazyGroupElement` and then do the precomputation. In my benchmarks I usually just convert all exponents to be non-negative beforehand to simulate available precomputations.

I have done some experiments relating inv to op cost and window size, but not for the other factors (all exponents always negative so far).

### Some rules I have so far:
- If precomputation is available for A1 and all exponents are negative plus cost of Op is not more than three times that of Inversion, we use A1. Less negative exponents would improve the situation for wNAF since the negative exponent handling introduces some additional inversion when computing the wNAF representation. That could be teased out with more benchmarks.
- If precomputation is not available for A1, then if Inv is double the cost of Op, wNAF becomes better at window size over 4. If Op is 2.5 times the cost of inv, wNAF is always better. How would this be affected by less negative exponents?

In general,  maybe one could create some kind of points formula here that calculates a score for each depending on inv to op cost ratio, window size and ratio of negative exponents to positive ones, and figure out a point boundary to decide between A1 and wNAF. I think this is too much work for the benefit though.

We could also just keep using only wNAF since since that usually is fine, especially in our own group implementations where Op costs are enormous compared to inversion (e.g. the type 1 group has inv cost at ~0.194 us/op and Op cost at ~670 us/op). Then we could save on added complexity. I guess the user could manually configure the lazy group to use the sliding window approach if they really want?

As a middle ground I could make use of the group-specific multiexp interface and create some rules just for the Mcl group. The default would still be wNAF for our other groups. This should be easier to do,  but then we would probably want to implement something to allow the user to precompute for inverted bases so we can reuse those precomputations for A1.

**Comment by rheitjoh** [comment]
> We could also just keep using only wNAF since since that usually is fine, especially in our own group implementations where Op costs are enormous compared to inversion (e.g. the type 1 group has inv cost at ~0.194 us/op and Op cost at ~670 us/op). Then we could save on added complexity. I guess the user could manually configure the lazy group to use the sliding window approach if they really want?

I will go with this for now.

**Comment by rheitjoh** [comment]
Think the discussion about how to handle inverted precomputations belongs here so reopening this.

Due to the fact that precomputations are bound to the specific `LazyGroupElement` base, it seems that we would have to store the inverted precomputation in this element as well (since the user will store the base in their key/public parameters etc.). So I would suggest adding a `precomputeInvPow` method that would precompute odd powers for the inverted base and store them in the base's `SmallExponentPrecomputation` object next to the regular precomputed odd powers.

`ensurePrecomputation` would then take a look at the exponent of each multi-exponentiation term and either perform the precomputation for the regular or inverted base depending on the sign of the exponent.

This approach would require the user to know ahead of time which element might be be exponentiated using a negative exponent. I think that is usually known ahead of time in cryptographic schemes though, right?

**Comment by JanBobolz** [comment]
We could also expand the `SmallExponentPrecomputation` with a second list with negated group elements. Then `ensureNegativePrecomputation()` (or whatever) could cleverly populate this list depending on whether there are already positive exponents, etc.

At least I feel that's preferable, given that the `SmallExponentPrecomputation` already has abstraction for retrieving negated precomputations.

**Comment by rheitjoh** [comment]
> We could also expand the SmallExponentPrecomputation with a second list with negated group elements
That was what I meant, yes. Not sure I understand the difference between your suggestion and mine except the adding of `ensureNegativePrecomputation`.

**Comment by JanBobolz** [comment]
I understood that your suggestion was to add a field to `LazyGroupElement`. My suggestion was to leave that completely untouched and instead add stuff to the class `SmallExponentPrecomputation`.
