### ISSUE TITLE
Reorganize packages

### ISSUE THREAD

**Issue by JanBobolz** [upbcuk/upb.crypto.math#39]
I noted the following:
- The `de/upb/crypto/math/interfaces` package contains some interfaces, but some interfaces are, instead, contained in a non-"interface" package (e.g., `de/upb/crypto/math/pairings/generic/BilinearGroup.java`). We should make this consistent. 
- `de/upb/crypto/math/structures/ec` feels like it belongs much more into the pairing or elliptic package.

My personal take on the first point would be to get rid of `de/upb/crypto/math/interfaces` and instead put all those interfaces into the packages they belong to. I think this makes for much better browsability to not have to completely switch package roots to find an interface (e.g., when you're browsing Javadoc, you're interested in, say, groups, and then you'd click "group", instead of "interfaces" and then "group").

Overall, I'd appreciate the following structure over what we have now: 

- groups (contains `GroupElement` interface, etc. directly)
  -  elliptic (`WeierstrassCurve`, `BilinearGroup` interfaces etc.)
     - type1.supersingular
     - type3.bn
     - nopairing (Secp256k1)
  - sn, etc.
- rings (`RingElement` interface, etc.)
  - zn, polynomial, etc. - also: `ExtensionField` and such, which is currently, confusingly, under `pairings`
- expressions, hash, random, serialization as before.

So elliptic, interfaces, pairings, structures would disappear from top-level and instead, we have this nice distinction between groups and rings at the top level.

**Comment by rheitjoh** [comment]
I would expect something like the Secp256k1 implementation to be under `elliptic` as well. Perhaps under `elliptic/impl`?

**Comment by JanBobolz** [comment]
> I would expect something like the Secp256k1 implementation to be under `elliptic` as well. Perhaps under `elliptic/impl`?

I've edited the post, that was a formatting error - I have not put sufficiently many spaces to indent the bullet point(s)

**Comment by JanBobolz** [comment]
I'd like to add to this: Ideally, I don't want any packages with the same "interfaces" anymore. Whatever is in `x/interfaces` should just be in `x`.

**Comment by rheitjoh** [comment]
Ok, looks good now.

**Comment by rheitjoh** [comment]
One thing that came up just now, is stuff like `Element`, `Structure`, and `Vector` classes. Those don't belong to any algebraic structure on their own. Maybe we add another top level package called `generic` or something similar for those?

**Comment by JanBobolz** [comment]
Aye. Maybe "structures" wasn't that bad for this. "generic" sounds good, too. You decide.

**Comment by rheitjoh** [comment]
Okay, I think something like this makes sense:
Have `groups` and `rings` as you said, but put them in package `structures`. Then `structures` can also contain a `misc` package where we can put stuff not related to any specific algebraic structure. Would mean an additional level of nesting.

**Comment by JanBobolz** [comment]
Agreed. Let's nest some more. 

Not a huge fan of "misc" - maybe just leave out that layer (e.g., instead of `structures/misc/vectors` just do  `structures/vectors` if that doesn't make things too messy?!

**Comment by rheitjoh** [comment]
Okay, I did what you suggested but with `cartesian` instead of `vectors` since that is also used elsewhere. 
A preliminary version is now on branch [remove-depr](https://github.com/upbcuk/upb.crypto.math/tree/remove-depr).
I still have to update some package docs and add new ones, but that can wait. You could start with #41 then.

**Comment by rheitjoh** [comment]
Addressed by #38
