### ISSUE TITLE
Prune unused stuff

### ISSUE THREAD

**Issue by JanBobolz** [upbcuk/upb.crypto.math#40]
I'd like to remove from the library:

- `RingMultiplicationImpl`
- `Seed` 
- `de/upb/crypto/math/structures/quotient`

This is because those classes are unused and don't really offer many compelling features on their own.

**Comment by rheitjoh** [comment]
If we delete the `quotient` stuff, we only support finite field extensions using polynomials of the form `x^d + c` for some constants `d`, `c`, while the `quotient` classes also supported more complex polynomials. Are we happy with that?

**Comment by JanBobolz** [comment]
I'm personally okay with that. The quotient implementation is theoretically nice, but in practice unnecessarily convoluted. If someone wants to support finite field extensions for other polynomials, they can (relatively easily) write their own FiniteFieldExtension class (alternatively, _we_ could write that for them, but I wouldn't base it on the current implementation, I think).

**Comment by rheitjoh** [comment]
Fixed with #38
