### ISSUE TITLE
Simplify Random interface

### ISSUE THREAD

**Issue by JanBobolz** [upbcuk/upb.crypto.math#41]
The whole `de/upb/crypto/math/random` package should be redesigned so that users can call the methods they're interested in statically without having to go through multiple classes to get the singleton.

**Comment by JanBobolz** [comment]
@rheitjoh please let me know as soon as there's a good moment to do this (involves refactoring, so I don't want to do it while you're moving packages).

**Comment by JanBobolz** [comment]
Done: 2cc573e6fe1e687ec1465715f0b3c393db023681 - will be merged with #38

**Comment by rheitjoh** [comment]
Fixed with #38
